### ISSUE TITLE
ReflectionException: Function gdpr:cleanup() does not exist

### ISSUE THREAD

**Issue by kohil55027** [OFFLINE-GmbH/oc-gdpr-plugin#63]
Step to reproduce this error

Turn on cron jobs and you will see at midnight every day the following error message

```
ReflectionException: Function gdpr:cleanup() does not exist in /home/example/public_html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:136
```

![image](https://user-images.githubusercontent.com/57869989/69010458-d9da7980-0957-11ea-9a76-8d324f374a99.png)

Stack Trace

```
ReflectionException: Function gdpr:cleanup() does not exist in /home/example/public_html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:136

Stack trace:

#0 /home/example/public_html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(136): ReflectionFunction->__construct('gdpr:cleanup')

#1 /home/example/public_html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(115): Illuminate\Container\BoundMethod::getCallReflector('gdpr:cleanup')

#2 /home/example/public_html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): Illuminate\Container\BoundMethod::getMethodDependencies(Object(October\Rain\Foundation\Application), 'gdpr:cleanup', Array)

#3 /home/example/public_html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(75): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()

#4 /home/example/public_html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\Container\BoundMethod::callBoundMethod(Object(October\Rain\Foundation\Application), 'gdpr:cleanup', Object(Closure))

#5 /home/example/public_html/vendor/laravel/framework/src/Illuminate/Container/Container.php(549): Illuminate\Container\BoundMethod::call(Object(October\Rain\Foundation\Application), 'gdpr:cleanup', Array, NULL)

#6 /home/example/public_html/vendor/laravel/framework/src/Illuminate/Console/Scheduling/CallbackEvent.php(74): Illuminate\Container\Container->call('gdpr:cleanup', Array)

#7 /home/example/public_html/vendor/laravel/framework/src/Illuminate/Console/Scheduling/ScheduleRunCommand.php(59): Illuminate\Console\Scheduling\CallbackEvent->run(Object(October\Rain\Foundation\Application))

#8 [internal function]: Illuminate\Console\Scheduling\ScheduleRunCommand->handle()

#9 /home/example/public_html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Array, Array)

#10 /home/example/public_html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()

#11 /home/example/public_html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\Container\BoundMethod::callBoundMethod(Object(October\Rain\Foundation\Application), Array, Object(Closure))

#12 /home/example/public_html/vendor/laravel/framework/src/Illuminate/Container/Container.php(549): Illuminate\Container\BoundMethod::call(Object(October\Rain\Foundation\Application), Array, Array, NULL)

#13 /home/example/public_html/vendor/laravel/framework/src/Illuminate/Console/Command.php(183): Illuminate\Container\Container->call(Array)

#14 /home/example/public_html/vendor/symfony/console/Command/Command.php(264): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))

#15 /home/example/public_html/vendor/laravel/framework/src/Illuminate/Console/Command.php(170): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))

#16 /home/example/public_html/vendor/symfony/console/Application.php(874): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))

#17 /home/example/public_html/vendor/symfony/console/Application.php(228): Symfony\Component\Console\Application->doRunCommand(Object(Illuminate\Console\Scheduling\ScheduleRunCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))

#18 /home/example/public_html/vendor/symfony/console/Application.php(130): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))

#19 /home/example/public_html/vendor/laravel/framework/src/Illuminate/Console/Application.php(88): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))

#20 /home/example/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(121): Illuminate\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))

#21 /home/example/public_html/artisan(34): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))

#22 {main}
```

Please can you fix this asap!

**Comment by tobias-kuendig** [comment]
This is a upstream bug: https://github.com/octobercms/october/issues/4771

I have implemented a workaround in 053dfe8 and released v2.0.14.

Would you mind changing the negative review on the Marketplace while you're updating? :wink:
